{% set name = "nodeenv" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ekalinin/nodeenv/archive/{{ version }}.tar.gz
  sha256: dbe5f7e966c6130038aa1966e432ff67a9e99f8e489d5ea8849b02770096389d

build:
  number: 0
  entry_points:
    - nodeenv = nodeenv:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - nodeenv --help
    # skip test_smoke because nodejs fails with:
    #   nodejs: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by nodejs)
    # let's assume it's an issue with the docker image
    - pytest tests -ra -k-test_smoke
  requires:
    - pytest
    - mock
    - coverage
  source_files:
    - tests

about:
  home: https://github.com/ekalinin/nodeenv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Node.js virtual environment builder

extra:
  recipe-maintainers:
    - nicoddemus
