{% set name = "nodeenv" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ekalinin/nodeenv/archive/{{ version }}.tar.gz
  sha256: 0d8ba86a1e4ab68bb16e8f1a1ac4f6261288012c72d4fa4a697949535c2c8d04

build:
  number: 0
  entry_points:
    - nodeenv = nodeenv:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python 2.7|>=3.7
    - setuptools  # depends on pkg_resources at runtime

test:
  commands:
    - nodeenv --help
    # skip test_smoke because nodejs fails with:
    #   nodejs: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by nodejs)
    # let's assume it's an issue with the docker image
    - pytest tests -ra -k "not test_smoke"
  requires:
    - pytest
    - mock
    - coverage
  source_files:
    - tests

about:
  home: https://github.com/ekalinin/nodeenv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Node.js virtual environment builder

extra:
  recipe-maintainers:
    - nicoddemus
